language: node_js
dist: trusty
group: edge
arch: arm64-graviton2
sudo: required
install: true
jobs:
  include:
    - stage: Build
      name: "Production"
      script:
        - npm install    || travis_terminate 1;
      workspaces:
        create:
          name: production_build
          paths:
            - packages/*/dist
            - packages/*/build

    - stage: Deploy
      if: branch = master_test_new_alpha_flow
      workspaces:
        use: production_build
      script:
        - git config --global user.email ${GITHUB_EMAIL}
        - git config --global user.name ${GITHUB_USER}
        - git remote set-url origin "https://wix:${GITHUB_TOKEN}@github.com/wix/pro-gallery.git" > /dev/null 2>&1
        - git checkout master_test_new_alpha_flow
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run fixLatestTag

notifications:
  email:
    recipients:
    - guyso@wix.com
